name: Build Package
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            cmd: npm run buildDebian
            artifact: linux-deb-package
            path: dist/app/*.deb
          - os: ubuntu-latest
            cmd: npm run buildRedhat
            artifact: linux-rpm-package
            path: dist/app/*.rpm
          - os: macos-13
            env:
              SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
            cmd: npm run buildMacIntel
            artifact: darwin-x86-package
            path: dist/app/*.zip
          - os: macos-13
            env:
              SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk
            cmd: npm run buildMacArm
            artifact: darwin-arm-package
            path: dist/app/*.zip
    env:
      SDKROOT: ${{ matrix.env.SDKROOT }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install --omit=optional
    - name: build package
      run: ${{ matrix.cmd }}
    - name: upload package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: ${{ matrix.path }}
